download = [
	"golang.org/x/benchmarks",
	"golang.org/x/blog",
	"golang.org/x/build",
	"golang.org/x/crypto",
	"golang.org/x/debug",
	"golang.org/x/example",
	"golang.org/x/exp",
	"golang.org/x/image",
	"golang.org/x/mobile",
	"golang.org/x/net",
	"golang.org/x/oauth2",
	"golang.org/x/playground",
	"golang.org/x/review",
	"golang.org/x/sys",
	"golang.org/x/talks",
	"golang.org/x/text",
	"golang.org/x/tools",
]

install = [
	"golang.org/x/tools/cmd/benchcmp",
	"golang.org/x/tools/cmd/callgraph",
	"golang.org/x/tools/cmd/cover",
	"golang.org/x/tools/cmd/digraph",
	"golang.org/x/tools/cmd/eg",
	"golang.org/x/tools/cmd/godex",
	"golang.org/x/tools/cmd/godoc",
	"golang.org/x/tools/cmd/goimports",
	"golang.org/x/tools/cmd/gomvpkg",
	"golang.org/x/tools/cmd/gorename",
	"golang.org/x/tools/cmd/gotype",
	"golang.org/x/tools/cmd/html2article",
	"golang.org/x/tools/cmd/oracle",
	"golang.org/x/tools/cmd/present",
	"golang.org/x/tools/cmd/ssadump",
	"golang.org/x/tools/cmd/stringer",
	"golang.org/x/tools/cmd/tipgodoc",
	"golang.org/x/tools/cmd/vet",
]